<?php
/*
Plugin Name: bikeWizard
Plugin URI: http://evang.dk/
Description: A wizard to pick the right Bullit bike that fits your needs
Version: 0.2
Author: Cecilie Karlsson
Author URI: http://evang.dk
License: GPL
*/
function showBikeWizard()
{

    ?>
        <script type="text/javascript">

            step = 0;

            function wizardButtonClicked()
            {
                step ++;

                switch(step) {
                    case 0:
                        document.getElementById("bike-wizard-progress-bar").style.width = '0%';
                        document.getElementById("bike-wizard-text-field").innerHTML = "welcome to the bike wizard.";
                        console.log(step);
                        break;
                    case 1:
                        document.getElementById("bike-wizard-progress-bar").style.width = '10%';
                        document.getElementById("bike-wizard-text-field").innerHTML =
                            "<div class='wrapper'>" +
                                " <h1> Step 1 - Choose Your Bike</h1> " +
                                "<div class='col-sm-4 ' >" +
                            "<img src='http://shop.larryvsharry.com/skin/frontend/lvsh/lvsh/images/homepage-full-bike-icon.png' class='imgbikewizard' >" +
                            "       <div class='radio'>" +
                            "           <label><input type='radio' name='optradio'>Fullbike</label> " +
                            "       </div> " +
                            "Full Bike\n" +
                            "If you are buying a Full bike, everything to ride safely and securely is included; reflectors complying with EU regulations, front and rear mudguards to keep that gritty spray away and an Abus, insurance approved ring lock." +
                                "</div>" +

                            "   <div class='col-sm-4'>" +
                            "<img src='http://shop.larryvsharry.com/skin/frontend/lvsh/lvsh/images/homepage-frame-kit-icon.png' class='imgbikewizard'>" +

                            "        <div class='radio'>" +
                            "           <label><input type='radio' name='optradio'>Framekit</label> " +
                            "          </div> " +
                            "Framekit\n" +
                            "If you have bought a Bullitt frame, here's what to expect; An aluminium frame, chromoly steel fork, steering rod and fittings, FSA 1 1/8 headsets, tapered headset and spacers and a sturdy kickstand. We also include our newly developed, interchangeable dropouts. Please specify whether you require dropouts for internal or external gears, or horizontal singlespeed dropouts with your order." +
                            "   </div>" +

                            "   <div class='col-sm-4'>" +
                            "<img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/e/b/ebullit_drivetrain2_test_3.png' class='imgbikewizard'>" +
                            "       <div class='radio'>" +
                            "           <label><input type='radio' name='optradio'>Steps EBullit Full Bike</label> " +
                            "       </div>" +
                            "The STePS eBullitt system includes a 250W, 36-volt electric drive unit, or motor, that will help get you up to speed, but cuts out at 15.5mph (25km/h). You can go faster than that if you want but any speeds over 15.5mph have to be generated by either pedalling or gravity alone. The drive unit produces a maximum torque of 50nm and weighs 3.2kg, making it one of the lightest on the market." +
                            "   </div> " +
                            "</div> ";
                        console.log(step);
                        break;
                    case 2:
                        document.getElementById("bike-wizard-progress-bar").style.width = '20%';
                        document.getElementById("bike-wizard-text-field").innerHTML =
                            "<div class='wrapper'>" +
                            "   <h1> Step 2 - Choose Your Color</h1>" +
                            " <div class='col-sm-4'>" +
                            "    <div class='radio'>" +
                           " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/c/i/circle-classic_1.png' class='imgcolorbikewizard'> " +
                            "       <label><input type='radio' name='optradio'>Classic</label> " +
                            "   </div> "+
                            "   <div class='radio'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/c/i/circle-race_1_1.png' class='imgcolorbikewizard'> " +
                            "       <label><input type='radio' name='optradio'>Race</label> " +
                            "   </div> " +
                            "   <div class='radio'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/p/e/pepper_color.png' class='imgcolorbikewizard'> " +
                            "       <label><input type='radio' name='optradio'>Pepper</label>" +
                            "   </div> " +
                            " </div>" +

                            " <div class='col-sm-4'>" +
                            "   <div class='radio'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/s/u/submarine_color.png' class='imgcolorbikewizard'> " +
                            "       <label><input type='radio' name='optradio'>Submarine</label>" +
                            "   </div> " +
                            "   <div class='radio'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/c/i/circle-bluebird_1.png' class='imgcolorbikewizard'> " +
                            "       <label><input type='radio' name='optradio'>Bluebird</label>" +
                            "   </div> " +
                            "   <div class='radio'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/c/i/circle-generic_2.png' class='imgcolorbikewizard'> " +
                            "       <label><input type='radio' name='optradio'>Milk Plus</label>" +
                            "   </div> " +
                            " </div>" +

                            " <div class='col-sm-4'>" +
                            "   <div class='radio'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/c/i/circle-clockwork_1.png' class='imgcolorbikewizard'> " +

                            "       <label><input type='radio' name='optradio'>Clockwork</label>" +
                            "   </div> " +
                            "   <div class='radio'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/c/i/circle-lizzard-king_1.png' class='imgcolorbikewizard'> " +

                            "       <label><input type='radio' name='optradio'>Lizardking</label>" +
                            "   </div> " +
                            "   <div class='radio'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/c/i/circle-raw_1.png' class='imgcolorbikewizard'> " +

                            "       <label><input type='radio' name='optradio'>Rå</label>" +
                            "   </div> " +
                            " </div>" +
                            "</div>";
                        console.log(step);
                        break;
                    case 3:
                        document.getElementById("bike-wizard-progress-bar").style.width = '30%';
                        document.getElementById("bike-wizard-text-field").innerHTML =
                            "<div class='wrapper'>" +
                            "   <h1> Step 3 - Model</h1>" +

                            "<div class='col-sm-6'>" +

                            "       <div class='radio'>" +
                            "           <label><input type='radio' name='optradio'>SINGLESPEED COMPONENT GROUP  </label> " +
                            "       </div> "+
                            "       <div class='radio'>" +
                            "           <label><input type='radio' name='optradio'>NEXUS 7 COMPONENT GROUP  </label> " +
                            "       </div> " +
                            "       <div class='radio'>" +
                            "           <label><input type='radio' name='optradio'>ALFINE 8 COMPONENT GROUP</label>" +
                            "       </div> " +
                            "       <div class='radio'>" +
                            "        <label><input type='radio' name='optradio'>ALFINE 8 GATES COMPONENT GROUP  </label>" +
                            "       </div> " +
                            "</div>" +

                            "<div class='col-sm-6'>" +
                            "   <div class='radio'>" +
                            "       <label><input type='radio' name='optradio'>ALFINE DI2 11/GATES COMPONENT GROUP </label>" +
                            "   </div> " +
                            "   <div class='radio'>" +
                            "       <label><input type='radio' name='optradio'>DEORE 20 COMPONENT GROUP  </label>" +
                            "   </div> " +
                            "   <div class='radio'>" +
                            "       <label><input type='radio' name='optradio'>XT 22 COMPONENT GROUP  </label>" +
                            "   </div> " +
                            "</div>" +
                            "<br>" +
                            "<br>" +
                            "<div class='small-12 columns tablecontent'><h2>Model comparison chart</h2>\n" +
                            "<button type='button' class='btn btn-info' data-toggle='collapse' data-target='#demo'>Click here to show comparison chart</button>" +
                             "<div id='demo' class='collapse'>" +
                            "<table  class='table table-striped'>\n" +
                            "<tbody>\n" +
                            "<tr>\n" +
                            "<td></td>\n" +
                            "<td style=\"width: 15px;\"></td>\n" +
                            "<td>\n" +
                            "<h4>Nexus 7</h4>\n" +
                            "</td>\n" +
                            "<td>\n" +
                            "<h4>Alfine 8</h4>\n" +
                            "</td>\n" +
                            "<td>\n" +
                            "<h4>Alfine 11 Di2/Gates Drive</h4>\n" +
                            "</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Drivetrain</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>7 speed internal Nexus hub</td>\n" +
                            "<td>8 speed internal Alfine hub</td>\n" +
                            "<td>11 speed Di2 Alfine/Gates CDX</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Wheels</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Alex Rims dm24/Novatec hubs</td>\n" +
                            "<td>Alex Rims dm24 /Alfine 8 hub</td>\n" +
                            "<td>Alex Rims Supra/Alfine 11 hub</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Tyres</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Schwalbe Marathon 1.75″</td>\n" +
                            "<td>Schwalbe Marathon 1.75″</td>\n" +
                            "<td>Schwalbe Marathon Supreme 1.60″</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Finishing Kit</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Alu seatpost, stem and riserbars</td>\n" +
                            "<td>Alu seatpost, stem and riserbars</td>\n" +
                            "<td>Alu seatpost, stem and riserbars</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Pedals</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Wellgo flat pedals</td>\n" +
                            "<td>Wellgo flat pedals</td>\n" +
                            "<td>Wellgo flat pedals</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Crankset/BB</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Truvativ/42T chainring<br>\n" +
                            "Truvativ powerspline bb</td>\n" +
                            "<td>Alfine crank/42T chainring<br>\n" +
                            "Hollowtech 2 bb</td>\n" +
                            "<td>Alfine crank/Gates chainring 46T<br>\n" +
                            "Hollowtech 2 bb</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Saddle</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Velo Racing</td>\n" +
                            "<td>Velo Racing</td>\n" +
                            "<td>Velo Racing</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Brakes</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Tektro hydraulic disc front/<br>\n" +
                            "back pedal rear brake</td>\n" +
                            "<td>Magura MT5 hydraulic disc<br>\n" +
                            "brakes w 180mm discs</td>\n" +
                            "<td>Magura MT5 hydraulic disc<br>\n" +
                            "brakes w 180mm discs</td>\n" +
                            "</tr>\n" +
                            "</tbody>\n" +
                            "</table>\n" +
                            "<table  class='table table-striped'>\n" +
                            "<tbody>\n" +
                            "<tr>\n" +
                            "<td></td>\n" +
                            "<td style=\"width: 15px;\"></td>\n" +
                            "<td>\n" +
                            "<h4>Deore 20</h4>\n" +
                            "</td>\n" +
                            "<td>\n" +
                            "<h4>XT 22</h4>\n" +
                            "</td>\n" +
                            "<td>\n" +
                            "<h4>Singlespeed</h4>\n" +
                            "</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Drivetrain</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>20 speed/Deore derailleurs/11-32 cassette</td>\n" +
                            "<td>22 speed/XT derailleurs/<br>\n" +
                            "11-42 cassette</td>\n" +
                            "<td>–</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Wheels</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Alex Rims dm24/Novatec hubs</td>\n" +
                            "<td>Alex Rims Supra/Novatec hubs</td>\n" +
                            "<td>Alex Rims dm24/ Novatec hubs</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Tyres</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Schwalbe Marathon 1.75″</td>\n" +
                            "<td>Schwalbe Kojak 1.35″</td>\n" +
                            "<td>Schwalbe Marathon 1.75″</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Finishing Kit</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Alu seatpost, stem and riserbars</td>\n" +
                            "<td>Thomson Trail bar, Elite seatpost, X4 stem and saddleclamp.</td>\n" +
                            "<td>Alu seatpost, stem and riserbar</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Pedals</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Wellgo flat pedals</td>\n" +
                            "<td>Wellgo flat pedals</td>\n" +
                            "<td>Wellgo flat pedals</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Crankset/BB</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Deore crank/40,24T chainrings<br>\n" +
                            "Hollowtech II bottom bracket</td>\n" +
                            "<td>XT crank/38,28T chainrings<br>\n" +
                            "Hollowtech II bottom bracket</td>\n" +
                            "<td>Truvativ (42t chainring)</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Saddle</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Velo Racing</td>\n" +
                            "<td>Velo Racing</td>\n" +
                            "<td>Velo Racing</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Brakes</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Tektro hydraulic disc<br>\n" +
                            "brakes w 180mm discs</td>\n" +
                            "<td>Shimano Zee hydraulic disc<br>\n" +
                            "brakes w 180mm discs</td>\n" +
                            "<td>Tektro hydraulic disc brakes<br>\n" +
                            "w 180mm discs</td>\n" +
                            "</tr>\n" +
                            "</tbody>\n" +
                            "</table>\n" +
                            "<table  class='table table-striped'>\n" +
                            "<tbody>\n" +
                            "<tr>\n" +
                            "<td></td>\n" +
                            "<td style=\"width: 15px;\"></td>\n" +
                            "<td>\n" +
                            "<h4>Zee 10</h4>\n" +
                            "</td>\n" +
                            "<td>\n" +
                            "<h4>Saint 10</h4>\n" +
                            "</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Drivetrain</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>10 speed/Zee derailleur/<br>\n" +
                            "11-36t cassette</td>\n" +
                            "<td>10 speed/Saint derailleur/<br>\n" +
                            "11-36t cassette</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Wheels</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Alex Rims DM24/ Zee hubs<br>\n" +
                            "(20mm thru axle front)</td>\n" +
                            "<td>Alex Rims Supra/ Saint hubs<br>\n" +
                            "(20mm thru axle)</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Tyres</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Schwalbe Marathon 1.75″</td>\n" +
                            "<td>Schwalbe Marathon Supreme 1.60″</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Finishing Kit</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Alu seatpost, stem and riserbars</td>\n" +
                            "<td>FSA Carbon bar and seatpost, FSA stem</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Pedals</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Wellgo flat pedals</td>\n" +
                            "<td>Wellgo flat pedals</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Crankset/BB</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Zee crank/36T chainring<br>\n" +
                            "Hollowtech 2 bb</td>\n" +
                            "<td>Saint crank/36T chainring</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Saddle</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Velo Racing</td>\n" +
                            "<td>Velo Racing</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Brakes</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Shimano Zee hydraulic disc<br>\n" +
                            "brakes w 203mm discs</td>\n" +
                            "<td>Shimano Saint hydraulic disc<br>\n" +
                            "brakes w 203mm discs</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "</tbody>\n" +
                            "</table>\n" +
                            "</div>" +
                            "</div>" +
                            "" +
                            "</div>";
                        console.log(step);
                        break ;
                    case 4:
                        document.getElementById("bike-wizard-progress-bar").style.width = '40%';
                        document.getElementById("bike-wizard-text-field").innerHTML =  "<div class='wrapper'>" +
                            "<h1> Step 4 - Customise</h1>" +
                            "All our models feature powerful, hydraulic disc brake systems for smoother, more controlled stopping. We have purposefully chosen brakes from leading manufacturers Shimano, Magura and Tektro and matched them to the most relevant component groups. For simple aftermarket servicing, we have also ensured our brakes have great brake pad durability and easy aftermarket servicing." +
                            "<br><br>" +
                            " <div class='col-sm-4'>" +
                            "<h3> Handlebars </h3>" +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>Riserbar</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>Flatbar</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>Cruiser</label>" +
                            "</div>" +
                            "</div> " +
                            " <div class='col-sm-4'>" +
                            "<h3> Seatposts </h3>" +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>Short</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>Long</label>" +
                            "</div>" +
                            "<p>The Bullitt is a one frame solution, designed to fit the greatest number of people and we have spent years tweaking geometry. A sloping top tube, short back-end and low bottom bracket means great manueveurability. We offer two different seatpost lengths and two different stem lengths to cater for different users and our Easyup Stemlifter means the cockpit can quickly and easily be raised to enable more space in the cargo area.</p>" +
                            "</div> " +
                            " <div class='col-sm-4'>" +
                            "<h3> Saddles </h3>" +
                            "  <div class='checkbox'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/l/black_1.png' class='imgbikewizard'> " +

                            "<br><br><label><input type='checkbox' value=''>Race Black</label>" +
                             "</div> " +
                            "  <div class='checkbox'> " +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/s/a/saddle_white.png' class='imgbikewizard'> " +
                            "<br><br><label><input type='checkbox' value=''>Race White</label>" +
                            "</div> " +

                            "  <div class='checkbox'> " +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/s/a/saddle_brown.png' class='imgbikewizard'> " +

                            "<br><label><input type='checkbox' value=''>Brooks B17, Brown </label>" +
                            "</div> " +

                            "  <div class='checkbox'> " +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/l/black_1_3.png' class='imgbikewizard'> " +

                            "<br><label><input type='checkbox' value=''>Brooks B17, Black  </label>" +
                            "</div> " +

                            "  <div class='checkbox'> " +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/s/a/saddle_brown_1.png' class='imgbikewizard'> " +

                            "<br><label><input type='checkbox' value=''>Brooks B67, Brown    </label>" +
                            "</div> " +

                            "  <div class='checkbox'> " +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/l/black_1_2.png' class='imgbikewizard'> " +
                            "<br><label><input type='checkbox' value=''>Brooks B67, Black  </label>" +
                            "</div>" +
                            "</div> " +
                            "</div>";
                        console.log(step);
                        break;
                    case 5:
                        document.getElementById("bike-wizard-progress-bar").style.width = '50%';
                        document.getElementById("bike-wizard-text-field").innerHTML = "<div class='wrapper'>" +
                            "<h1> Step 5 - Accessories</h1>" +
                            " <div class='col-sm-4'>" +
                            "  <div class='checkbox'> " +
                            "<img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/d/o/dogcage_1.png' class='imgbikewizard' >" +
                            "<label><input type='checkbox' value=''>Canopy</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<img src='http://shop.larryvsharry.com/skin/frontend/lvsh/lvsh/images/alubox_1.png' class='imgbikewizard' >" +
                            "<label><input type='checkbox' value=''>Damper kit</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<img src='http://shop.larryvsharry.com/skin/frontend/lvsh/lvsh/images/honeycompboard.png' class='imgbikewizard' >" +
                            "<label><input type='checkbox' value=''>Honeycomb board</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/7/b/7b31bee8-1a42-45ba-b713-d3bd4086d8d9_lan.png' class='imgbikewizard' >" +
                            "<label><input type='checkbox' value=''>Convoy box</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/a/l/alubox.png' class='imgbikewizard >" +
                            "<label><input type='checkbox' value=''>Aluminium box</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/p/l/plastbox.png' class='imgbikewizard' >" +
                            "<label><input type='checkbox' value=''>Plastic box</label>" +
                            "</div> " +
                            "</div>" +

                            " <div class='col-sm-4'>" +
                            "<h3> BBX </h3>" +

                        "<img src='http://shop.larryvsharry.com/skin/frontend/lvsh/lvsh/images/sidepanel_kit.png' class='imgbikewizard' >" +




                        "  <div class='radio'> " +
                            "<img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/b/bbx-sidepanel-kit-indigo.png' class='imgbikewizard' >" +
                            "<label><input type='radio' value='optradio'>Blue</label>" +
                            "</div> " +

                            "  <div class='radio'> " +
                            "<img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/b/bbx-sidepanel-kit-race.png' class='imgbikewizard' >" +

                            "<label><input type='radio' value='optradio'>Green</label>" +
                            "</div> " +
                            "  <div class='radio'> " +
                            "<img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/b/bbx-sidepanel-kit-submarine_1.png' class='imgbikewizard' >" +

                            "<label><input type='radio' value='optradio'>Yellow</label>" +
                            "</div> " +
                            "</div>" +

                            " <div class='col-sm-4'>" +
                            "<h3> Billboard </h3>" +
                            "<img src='http://shop.larryvsharry.com/skin/frontend/lvsh/lvsh/images/billboard.png' class='imgbikewizard' >" +

                            "  <div class='radio'> " +
                            "<img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/3/2/32_1_1.png' class='imgcolorbikewizard' >" +
                            "<label><input type='radio' value='optradio'>1 </label>" +
                            "</div> " +

                            "  <div class='radio'> " +
                            "<img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/3/2/323_2.png' class='imgcolorbikewizard' >" +
                            "<label><input type='radio' value='optradio'>2   </label>" +
                            "</div> " +

                            "  <div class='radio'> " +
                            "<img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/5/0/502_4.png' class='imgcolorbikewizard' >" +
                            "<label><input type='radio' value='optradio'>3  </label>" +
                            "</div> " +

                            "  <div class='radio'> " +
                            "<img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/5/0/503_3.png' class='imgcolorbikewizard' >" +

                            "<label><input type='radio' value='optradio'>4  </label>" +
                            "</div> " +
                            "  <div class='radio'> " +
                            "<img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/5/0/504_1_1.png' class='imgcolorbikewizard' >" +

                            "<label><input type='radio' value='optradio'>5  </label>" +
                            "</div> " +
                            "  <div class='radio'> " +
                            "<img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/5/0/506_3.png' class='imgcolorbikewizard' >" +

                            "<label><input type='radio' value='optradio'>6  </label>" +
                            "</div> " +
                            "  <div class='radio'> " +
                            "<img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/5/0/508_3.png' class='imgcolorbikewizard' >" +

                            "<label><input type='radio' value='optradio'>7  </label>" +
                            "</div> " +

                            "</div>" +
                               " <br> <br>" +
                            " <div class='bikenote' >  <p >The BBX side + cover, Foldable seat and Canopy all need the HCB.<p> </div> " +
                            "</div>";
                        console.log(step);
                        break;
                    case 6:
                        document.getElementById("bike-wizard-progress-bar").style.width = '60%';
                        document.getElementById("bike-wizard-text-field").innerHTML = "<div class='wrapper'>" +
                            "<h1> Step 6 - Extras</h1>" +
                            "<div class='col-sm-6'>" +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>DYNAMO 20\" FRONT WHEEL (ALFINE/ALEX DM24)  </label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>REELIGHTS </label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>CROMO KICKSTAND  )</label>" +
                            "</div>" +
                            "</div> " +
                            "<div class='col-sm-6'>" +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>ABUS 5400 GRANITE U-LOCK</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>ABUS BORDO 6500 GRANIT X PLUS  </label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>ABUS 9100 IVY CHAIN LOCK </label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>ABUS BORDO + DETECTO 8077 ALARM  </label>" +
                            "</div>" +
                            "</div> " +


                            "</div>";
                        console.log(step);
                        break;
                    case 7:
                        document.getElementById("bike-wizard-progress-bar").style.width = '70%';
                        document.getElementById("bike-wizard-text-field").innerHTML = "<div class='wrapper'>" +
                            "<h1>Step 7 - What you are buying</h1>" +
                            "<p> Here you will find a list of what items you have checked off, and recommendations on what you are missing. <br>" +
                            "Here you can check off things if you have regret or do not want to buy them. <br> " +
                            "If everything seems as it is supposed to, then just click next and go to the payment site. </p>" +
                            "</div>";
                        console.log(step);
                        break;
                    case 8:
                        document.getElementById("bike-wizard-progress-bar").style.width = '80%';
                        document.getElementById("bike-wizard-text-field").innerHTML = "<div class='wrapper'>" +
                            "<h1>Step 8 - Payment</h1>" +
                            "<p> This is the payment area. Where there will be a form where you can pay. " +
                            " <form class='form-horizontal'>" +
                            "    <div class='form-group'>" +
                            "      <label class='col-sm-2 control-label'>Email</label>" +
                            "      <div class='col-sm-10'>" +
                            "        <input class='form-control' id='focusedInput' type='text' value='Enter email...'>" +
                            "      </div>" +
                            "    </div>" +

                            "    <div class='form-group'>" +
                            "      <label class='col-sm-2 control-label'>Name</label>" +
                            "      <div class='col-sm-10'>" +
                            "        <input class='form-control' id='focusedInput' type='text' value='Enter Name...'>" +
                            "      </div>" +
                            "    </div>" +

                            "    <div class='form-group'>" +
                            "      <label class='col-sm-2 control-label'>Adress</label>" +
                            "      <div class='col-sm-10'>" +
                            "        <input class='form-control' id='focusedInput' type='text' value='Enter Adress...'>" +
                            "      </div>" +
                            "    </div>" +
                            "    <div class='form-group'>" +
                            "      <label class='col-sm-2 control-label'>Cardnumber</label>" +
                            "      <div class='col-sm-10'>" +
                            "        <input class='form-control' id='focusedInput' type='text' value='Enter Cardnumber...'>" +
                            "      </div>" +
                            "    </div>" +
                            "<div class='form-group'> " +
                            "      <div class='col-sm-offset-2 col-sm-10'>" +
                            "        <button type='submit' class='btn btn-default'>Submit</button>" +
                            "      </div>" +
                            "    </div>" +
                            "  </form>" +
                            "</p>" +
                            "</div>";
                        console.log(step);
                        break;
                    case 9:
                        document.getElementById("bike-wizard-progress-bar").style.width = '90%';
                        document.getElementById("bike-wizard-text-field").innerHTML = "<div class='wrapper'>" +
                            "<h1>Step 9 - Order confirmation</h1>" +
                            "<p> Here you can see you order, that are payed and waiting to be packed and shipped </p>" +
                            "</div>";
                        console.log(step);
                        break;
                    case 10:
                        document.getElementById("bike-wizard-progress-bar").style.width = '100%';
                        document.getElementById("bike-wizard-text-field").innerHTML = "<div class='wrapper'>" +
                            "<h1>Step 10 - Thank you for your purchase </h1>" +
                            "<p>Here is some other things you might find interesting </p>" +
                            "</div>";
                        console.log(step);
                        break;
                    case 11:
                        if (this.step > 10) {this.step = 10;}
                        document.getElementById("bike-wizard-progress-bar").style.width = '100%';
                        document.getElementById("bike-wizard-text-field").innerHTML ="<div class='wrapper'>" +
                            "<h1>Step 10 - Thank you for your purchase </h1>" +
                            "<p>Here is some other things you might find interesting </p>" +
                            "</div>";
                        console.log(step);
                        break;
                    default:
                       // document.getElementById("bike-wizard-progress-bar").style.width = '100%';
                      //  document.getElementById("bike-wizard-text-field").innerHTML = "Step 10...";
                        console.log(step);
                        break;

                }


            }

            function wizardButtonClickedback() {
                step--;

                switch(step) {
                    case -1:
                        if (this.step < 0) {
                            this.step = 0;
                        }
                        document.getElementById("bike-wizard-progress-bar").style.width = '0%';
                        document.getElementById("bike-wizard-text-field").innerHTML = "Welcome to the bike wizard. Here you can custom build your own Bullit.";
                        console.log(step);
                        break;
                    case 0:

                        document.getElementById("bike-wizard-progress-bar").style.width = '0%';
                        document.getElementById("bike-wizard-text-field").innerHTML = "Introduction\n" +
                            "\n" +
                            "Bullitt’s are as different as the people who ride them and with years of experience, we have developed what we believe to be the ultimate, do-it-all cargo bike.\n" +
                            "\n" +
                            "Designed, built and ridden daily in Copenhagen and across the globe.\n" +
                            "9 colour options and a diverse component and accessory line.\n" +
                            "\n" +
                            "With quick delivery and availability, competitive pricing and a highly developed system of components and accessories, the Bullitt is the quickest, most flexible and durable solution currently on the market.\n" +
                            "\n" +
                            "This buyer’s guide is designed to help you choose the correct Bullitt model and pair you with the most appropriate accessories for your needs.";
                        console.log(step);
                        break;
                    case 1:
                        document.getElementById("bike-wizard-progress-bar").style.width = '10%';
                        document.getElementById("bike-wizard-text-field").innerHTML =  "<div class='wrapper'>" +
                            " <h1> Step 1 - Choose Your Bike</h1> " +
                            "<div class='col-sm-4 ' >" +
                            "<img src='http://shop.larryvsharry.com/skin/frontend/lvsh/lvsh/images/homepage-full-bike-icon.png' class='imgbikewizard' >" +
                            "       <div class='radio'>" +
                            "           <label><input type='radio' name='optradio'>Fullbike</label> " +
                            "       </div> " +
                            "Full Bike\n" +
                            "If you are buying a Full bike, everything to ride safely and securely is included; reflectors complying with EU regulations, front and rear mudguards to keep that gritty spray away and an Abus, insurance approved ring lock." +
                            "</div>" +

                            "   <div class='col-sm-4'>" +
                            "<img src='http://shop.larryvsharry.com/skin/frontend/lvsh/lvsh/images/homepage-frame-kit-icon.png' class='imgbikewizard'>" +

                            "        <div class='radio'>" +
                            "           <label><input type='radio' name='optradio'>Framekit</label> " +
                            "          </div> " +
                            "Framekit\n" +
                            "If you have bought a Bullitt frame, here's what to expect; An aluminium frame, chromoly steel fork, steering rod and fittings, FSA 1 1/8 headsets, tapered headset and spacers and a sturdy kickstand. We also include our newly developed, interchangeable dropouts. Please specify whether you require dropouts for internal or external gears, or horizontal singlespeed dropouts with your order." +
                            "   </div>" +

                            "   <div class='col-sm-4'>" +
                            "<img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/e/b/ebullit_drivetrain2_test_3.png' class='imgbikewizard'>" +
                            "       <div class='radio'>" +
                            "           <label><input type='radio' name='optradio'>Steps EBullit Full Bike</label> " +
                            "       </div>" +
                            "The STePS eBullitt system includes a 250W, 36-volt electric drive unit, or motor, that will help get you up to speed, but cuts out at 15.5mph (25km/h). You can go faster than that if you want but any speeds over 15.5mph have to be generated by either pedalling or gravity alone. The drive unit produces a maximum torque of 50nm and weighs 3.2kg, making it one of the lightest on the market." +
                            "   </div> " +
                            "</div> ";
                        console.log(step);
                        break;
                    case 2:
                        document.getElementById("bike-wizard-progress-bar").style.width = '20%';
                        document.getElementById("bike-wizard-text-field").innerHTML =  "<div class='wrapper'>" +
                            "   <h1> Step 2 - Choose Your Color</h1>" +
                            " <div class='col-sm-4'>" +
                            "    <div class='radio'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/c/i/circle-classic_1.png' class='imgcolorbikewizard'> " +
                            "       <label><input type='radio' name='optradio'>Classic</label> " +
                            "   </div> "+
                            "   <div class='radio'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/c/i/circle-race_1_1.png' class='imgcolorbikewizard'> " +
                            "       <label><input type='radio' name='optradio'>Race</label> " +
                            "   </div> " +
                            "   <div class='radio'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/p/e/pepper_color.png' class='imgcolorbikewizard'> " +
                            "       <label><input type='radio' name='optradio'>Pepper</label>" +
                            "   </div> " +
                            " </div>" +

                            " <div class='col-sm-4'>" +
                            "   <div class='radio'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/s/u/submarine_color.png' class='imgcolorbikewizard'> " +
                            "       <label><input type='radio' name='optradio'>Submarine</label>" +
                            "   </div> " +
                            "   <div class='radio'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/c/i/circle-bluebird_1.png' class='imgcolorbikewizard'> " +
                            "       <label><input type='radio' name='optradio'>Bluebird</label>" +
                            "   </div> " +
                            "   <div class='radio'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/c/i/circle-generic_2.png' class='imgcolorbikewizard'> " +
                            "       <label><input type='radio' name='optradio'>Milk Plus</label>" +
                            "   </div> " +
                            " </div>" +

                            " <div class='col-sm-4'>" +
                            "   <div class='radio'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/c/i/circle-clockwork_1.png' class='imgcolorbikewizard'> " +

                            "       <label><input type='radio' name='optradio'>Clockwork</label>" +
                            "   </div> " +
                            "   <div class='radio'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/c/i/circle-lizzard-king_1.png' class='imgcolorbikewizard'> " +

                            "       <label><input type='radio' name='optradio'>Lizardking</label>" +
                            "   </div> " +
                            "   <div class='radio'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/c/i/circle-raw_1.png' class='imgcolorbikewizard'> " +

                            "       <label><input type='radio' name='optradio'>Rå</label>" +
                            "   </div> " +
                            " </div>" +
                            "</div>";
                        console.log(step);
                        break;
                    case 3:
                        document.getElementById("bike-wizard-progress-bar").style.width = '30%';
                        document.getElementById("bike-wizard-text-field").innerHTML = "<div class='wrapper'>" +
                            "   <h1> Step 3 - Model</h1>" +

                            "<div class='col-sm-6'>" +

                            "       <div class='radio'>" +
                            "           <label><input type='radio' name='optradio'>SINGLESPEED COMPONENT GROUP  </label> " +
                            "       </div> "+
                            "       <div class='radio'>" +
                            "           <label><input type='radio' name='optradio'>NEXUS 7 COMPONENT GROUP  </label> " +
                            "       </div> " +
                            "       <div class='radio'>" +
                            "           <label><input type='radio' name='optradio'>ALFINE 8 COMPONENT GROUP</label>" +
                            "       </div> " +
                            "       <div class='radio'>" +
                            "        <label><input type='radio' name='optradio'>ALFINE 8 GATES COMPONENT GROUP  </label>" +
                            "       </div> " +
                            "</div>" +

                            "<div class='col-sm-6'>" +
                            "   <div class='radio'>" +
                            "       <label><input type='radio' name='optradio'>ALFINE DI2 11/GATES COMPONENT GROUP </label>" +
                            "   </div> " +
                            "   <div class='radio'>" +
                            "       <label><input type='radio' name='optradio'>DEORE 20 COMPONENT GROUP  </label>" +
                            "   </div> " +
                            "   <div class='radio'>" +
                            "       <label><input type='radio' name='optradio'>XT 22 COMPONENT GROUP  </label>" +
                            "   </div> " +
                            "</div>" +
                            "<br>" +
                            "<br>" +
                            "<div class='small-12 columns tablecontent'><h2>Model comparison chart</h2>\n" +
                            "<button type='button' class='btn btn-info' data-toggle='collapse' data-target='#demo'>Click here to show comparison chart</button>" +
                            "<div id='demo' class='collapse'>" +
                            "<table  class='table table-striped'>\n" +
                            "<tbody>\n" +
                            "<tr>\n" +
                            "<td></td>\n" +
                            "<td style=\"width: 15px;\"></td>\n" +
                            "<td>\n" +
                            "<h4>Nexus 7</h4>\n" +
                            "</td>\n" +
                            "<td>\n" +
                            "<h4>Alfine 8</h4>\n" +
                            "</td>\n" +
                            "<td>\n" +
                            "<h4>Alfine 11 Di2/Gates Drive</h4>\n" +
                            "</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Drivetrain</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>7 speed internal Nexus hub</td>\n" +
                            "<td>8 speed internal Alfine hub</td>\n" +
                            "<td>11 speed Di2 Alfine/Gates CDX</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Wheels</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Alex Rims dm24/Novatec hubs</td>\n" +
                            "<td>Alex Rims dm24 /Alfine 8 hub</td>\n" +
                            "<td>Alex Rims Supra/Alfine 11 hub</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Tyres</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Schwalbe Marathon 1.75″</td>\n" +
                            "<td>Schwalbe Marathon 1.75″</td>\n" +
                            "<td>Schwalbe Marathon Supreme 1.60″</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Finishing Kit</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Alu seatpost, stem and riserbars</td>\n" +
                            "<td>Alu seatpost, stem and riserbars</td>\n" +
                            "<td>Alu seatpost, stem and riserbars</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Pedals</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Wellgo flat pedals</td>\n" +
                            "<td>Wellgo flat pedals</td>\n" +
                            "<td>Wellgo flat pedals</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Crankset/BB</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Truvativ/42T chainring<br>\n" +
                            "Truvativ powerspline bb</td>\n" +
                            "<td>Alfine crank/42T chainring<br>\n" +
                            "Hollowtech 2 bb</td>\n" +
                            "<td>Alfine crank/Gates chainring 46T<br>\n" +
                            "Hollowtech 2 bb</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Saddle</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Velo Racing</td>\n" +
                            "<td>Velo Racing</td>\n" +
                            "<td>Velo Racing</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Brakes</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Tektro hydraulic disc front/<br>\n" +
                            "back pedal rear brake</td>\n" +
                            "<td>Magura MT5 hydraulic disc<br>\n" +
                            "brakes w 180mm discs</td>\n" +
                            "<td>Magura MT5 hydraulic disc<br>\n" +
                            "brakes w 180mm discs</td>\n" +
                            "</tr>\n" +
                            "</tbody>\n" +
                            "</table>\n" +
                            "<table  class='table table-striped'>\n" +
                            "<tbody>\n" +
                            "<tr>\n" +
                            "<td></td>\n" +
                            "<td style=\"width: 15px;\"></td>\n" +
                            "<td>\n" +
                            "<h4>Deore 20</h4>\n" +
                            "</td>\n" +
                            "<td>\n" +
                            "<h4>XT 22</h4>\n" +
                            "</td>\n" +
                            "<td>\n" +
                            "<h4>Singlespeed</h4>\n" +
                            "</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Drivetrain</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>20 speed/Deore derailleurs/11-32 cassette</td>\n" +
                            "<td>22 speed/XT derailleurs/<br>\n" +
                            "11-42 cassette</td>\n" +
                            "<td>–</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Wheels</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Alex Rims dm24/Novatec hubs</td>\n" +
                            "<td>Alex Rims Supra/Novatec hubs</td>\n" +
                            "<td>Alex Rims dm24/ Novatec hubs</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Tyres</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Schwalbe Marathon 1.75″</td>\n" +
                            "<td>Schwalbe Kojak 1.35″</td>\n" +
                            "<td>Schwalbe Marathon 1.75″</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Finishing Kit</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Alu seatpost, stem and riserbars</td>\n" +
                            "<td>Thomson Trail bar, Elite seatpost, X4 stem and saddleclamp.</td>\n" +
                            "<td>Alu seatpost, stem and riserbar</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Pedals</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Wellgo flat pedals</td>\n" +
                            "<td>Wellgo flat pedals</td>\n" +
                            "<td>Wellgo flat pedals</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Crankset/BB</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Deore crank/40,24T chainrings<br>\n" +
                            "Hollowtech II bottom bracket</td>\n" +
                            "<td>XT crank/38,28T chainrings<br>\n" +
                            "Hollowtech II bottom bracket</td>\n" +
                            "<td>Truvativ (42t chainring)</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Saddle</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Velo Racing</td>\n" +
                            "<td>Velo Racing</td>\n" +
                            "<td>Velo Racing</td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Brakes</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Tektro hydraulic disc<br>\n" +
                            "brakes w 180mm discs</td>\n" +
                            "<td>Shimano Zee hydraulic disc<br>\n" +
                            "brakes w 180mm discs</td>\n" +
                            "<td>Tektro hydraulic disc brakes<br>\n" +
                            "w 180mm discs</td>\n" +
                            "</tr>\n" +
                            "</tbody>\n" +
                            "</table>\n" +
                            "<table  class='table table-striped'>\n" +
                            "<tbody>\n" +
                            "<tr>\n" +
                            "<td></td>\n" +
                            "<td style=\"width: 15px;\"></td>\n" +
                            "<td>\n" +
                            "<h4>Zee 10</h4>\n" +
                            "</td>\n" +
                            "<td>\n" +
                            "<h4>Saint 10</h4>\n" +
                            "</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Drivetrain</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>10 speed/Zee derailleur/<br>\n" +
                            "11-36t cassette</td>\n" +
                            "<td>10 speed/Saint derailleur/<br>\n" +
                            "11-36t cassette</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Wheels</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Alex Rims DM24/ Zee hubs<br>\n" +
                            "(20mm thru axle front)</td>\n" +
                            "<td>Alex Rims Supra/ Saint hubs<br>\n" +
                            "(20mm thru axle)</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Tyres</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Schwalbe Marathon 1.75″</td>\n" +
                            "<td>Schwalbe Marathon Supreme 1.60″</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Finishing Kit</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Alu seatpost, stem and riserbars</td>\n" +
                            "<td>FSA Carbon bar and seatpost, FSA stem</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Pedals</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Wellgo flat pedals</td>\n" +
                            "<td>Wellgo flat pedals</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Crankset/BB</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Zee crank/36T chainring<br>\n" +
                            "Hollowtech 2 bb</td>\n" +
                            "<td>Saint crank/36T chainring</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Saddle</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Velo Racing</td>\n" +
                            "<td>Velo Racing</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "<tr>\n" +
                            "<td><strong>Brakes</strong></td>\n" +
                            "<td></td>\n" +
                            "<td>Shimano Zee hydraulic disc<br>\n" +
                            "brakes w 203mm discs</td>\n" +
                            "<td>Shimano Saint hydraulic disc<br>\n" +
                            "brakes w 203mm discs</td>\n" +
                            "<td></td>\n" +
                            "</tr>\n" +
                            "</tbody>\n" +
                            "</table>\n" +
                            "</div>" +
                            "</div>" +
                            "" +
                            "</div>";
                        console.log(step);
                        break;
                    case 4:
                        document.getElementById("bike-wizard-progress-bar").style.width = '40%';
                        document.getElementById("bike-wizard-text-field").innerHTML =   "<div class='wrapper'>" +
                            "<h1> Step 4 - Customise</h1>" +
                            "All our models feature powerful, hydraulic disc brake systems for smoother, more controlled stopping. We have purposefully chosen brakes from leading manufacturers Shimano, Magura and Tektro and matched them to the most relevant component groups. For simple aftermarket servicing, we have also ensured our brakes have great brake pad durability and easy aftermarket servicing." +
                            "<br><br>" +
                            " <div class='col-sm-4'>" +
                            "<h3> Handlebars </h3>" +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>Riserbar</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>Flatbar</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>Cruiser</label>" +
                            "</div>" +
                            "</div> " +
                            " <div class='col-sm-4'>" +
                            "<h3> Seatposts </h3>" +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>Short</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>Long</label>" +
                            "</div>" +
                            "<p>The Bullitt is a one frame solution, designed to fit the greatest number of people and we have spent years tweaking geometry. A sloping top tube, short back-end and low bottom bracket means great manueveurability. We offer two different seatpost lengths and two different stem lengths to cater for different users and our Easyup Stemlifter means the cockpit can quickly and easily be raised to enable more space in the cargo area.</p>" +
                            "</div> " +
                            " <div class='col-sm-4'>" +
                            "<h3> Saddles </h3>" +
                            "  <div class='checkbox'>" +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/l/black_1.png' class='imgbikewizard'> " +

                            "<label><input type='checkbox' value=''>Race Black</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/s/a/saddle_white.png' class='imgbikewizard'> " +
                            "<label><input type='checkbox' value=''>Race White</label>" +
                            "</div> " +

                            "  <div class='checkbox'> " +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/s/a/saddle_brown.png' class='imgbikewizard'> " +

                            "<label><input type='checkbox' value=''>Brooks B17, Brown </label>" +
                            "</div> " +

                            "  <div class='checkbox'> " +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/l/black_1_3.png' class='imgbikewizard'> " +

                            "<label><input type='checkbox' value=''>Brooks B17, Black  </label>" +
                            "</div> " +

                            "  <div class='checkbox'> " +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/s/a/saddle_brown_1.png' class='imgbikewizard'> " +

                            "<label><input type='checkbox' value=''>Brooks B67, Brown    </label>" +
                            "</div> " +

                            "  <div class='checkbox'> " +
                            " <img src='http://shop.larryvsharry.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/l/black_1_2.png' class='imgbikewizard'> " +
                            "<label><input type='checkbox' value=''>Brooks B67, Black  </label>" +
                            "</div>" +
                            "</div> " +
                            "</div>";
                        console.log(step);
                        break;
                    case 5:
                        document.getElementById("bike-wizard-progress-bar").style.width = '50%';
                        document.getElementById("bike-wizard-text-field").innerHTML =  "<div class='wrapper'>" +
                            "<h1> Step 5 - Accessories</h1>" +
                            " <div class='col-sm-4'>" +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>Canopy</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>Damper kit</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>Honeycomb board (HCB)</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>Convoy box</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>Aluminium box</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>Plastic box</label>" +
                            "</div> " +
                            "</div>" +

                            " <div class='col-sm-4'>" +
                            "<h3> BBX </h3>" +
                            "  <div class='radio'> " +
                            "<label><input type='radio' value='optradio'>color1</label>" +
                            "</div> " +

                            "  <div class='radio'> " +
                            "<label><input type='radio' value='optradio'>color2</label>" +
                            "</div> " +
                            "  <div class='radio'> " +
                            "<label><input type='radio' value='optradio'>color3 </label>" +
                            "</div> " +
                            "</div>" +

                            " <div class='col-sm-4'>" +
                            "<h3> Billboard </h3>" +
                            "  <div class='radio'> " +
                            "<label><input type='radio' value='optradio'>1 </label>" +
                            "</div> " +
                            "  <div class='radio'> " +
                            "<label><input type='radio' value='optradio'>2   </label>" +
                            "</div> " +
                            "  <div class='radio'> " +
                            "<label><input type='radio' value='optradio'>3  </label>" +
                            "</div> " +
                            "  <div class='radio'> " +
                            "<label><input type='radio' value='optradio'>4  </label>" +
                            "</div> " +
                            "  <div class='radio'> " +
                            "<label><input type='radio' value='optradio'>5  </label>" +
                            "</div> " +
                            "  <div class='radio'> " +
                            "<label><input type='radio' value='optradio'>6  </label>" +
                            "</div> " +
                            "  <div class='radio'> " +
                            "<label><input type='radio' value='optradio'>7  </label>" +
                            "</div> " +
                            "  <div class='radio'> " +
                            "<label><input type='radio' value='optradio'>8  </label>" +
                            "</div> " +
                            "  <div class='radio'> " +
                            "<label><input type='radio' value='optradio'>9  </label>" +
                            "</div> " +
                            "</div>" +
                            "<p>The BBX side + cover, Foldable seat and Canopy all need the HCB.<p>" +
                            "</div>";
                        console.log(step);
                        break;
                    case 6:
                        document.getElementById("bike-wizard-progress-bar").style.width = '60%';
                        document.getElementById("bike-wizard-text-field").innerHTML = "<div class='wrapper'>" +
                            "<h1> Step 6 - Extras</h1>" +
                            "<div class='col-sm-6'>" +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>DYNAMO 20\" FRONT WHEEL (ALFINE/ALEX DM24)  </label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>REELIGHTS </label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>CROMO KICKSTAND  )</label>" +
                            "</div>" +
                            "</div> " +
                            "<div class='col-sm-6'>" +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>ABUS 5400 GRANITE U-LOCK</label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>ABUS BORDO 6500 GRANIT X PLUS  </label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>ABUS 9100 IVY CHAIN LOCK </label>" +
                            "</div> " +
                            "  <div class='checkbox'> " +
                            "<label><input type='checkbox' value=''>ABUS BORDO + DETECTO 8077 ALARM  </label>" +
                            "</div> " +
                            "</div> " +


                            "</div>";
                        console.log(step);
                        break;
                    case 7:
                        document.getElementById("bike-wizard-progress-bar").style.width = '70%';
                        document.getElementById("bike-wizard-text-field").innerHTML = "<div class='wrapper'>" +
                            "<h1>Step 7 - What you are buying</h1>" +
                            "<p> Here you will find a list of what items you have checked off, and recommendations on what you are missing. <br>" +
                            "Here you can check off things if you have regret or do not want to buy them. <br> " +
                            "If everything seems as it is supposed to, then just click next and go to the payment site. </p>" +
                            "</div>";
                        console.log(step);
                        break;
                    case 8:
                        document.getElementById("bike-wizard-progress-bar").style.width = '80%';
                        document.getElementById("bike-wizard-text-field").innerHTML = "<div class='wrapper'>" +
                            "<h1>Step 8 - Payment</h1>" +
                            "<p> This is the payment area. Where there will be a form where you can pay. </p>" +
                            "</div>";
                        console.log(step);
                        break;
                    case 9:
                        document.getElementById("bike-wizard-progress-bar").style.width = '90%';
                        document.getElementById("bike-wizard-text-field").innerHTML = "<div class='wrapper'>" +
                            "<h1>Step 9 - Order confirmation</h1>" +
                            "<p> Here you can see you order, that are payed and waiting to be packed and shipped </p>" +
                            "</div>";
                        console.log(step);
                        break;
                    default:
                        console.log(step);
                        // document.getElementById("bike-wizard-progress-bar").style.width = '10%';
                       // document.getElementById("bike-wizard-text-field").innerHTML = "Step 1...";
                        break;

                }
            }
        </script>

        <div class="progress">
            <div class="progress-bar" id="bike-wizard-progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:0%">
            <span class="sr-only">70% Complete</span>
            </div>
        </div>

        <div id="bike-wizard-text-field">
<br>
            Bullitt’s are as different as the people who ride them and with years of experience, we have developed what we believe to be the ultimate, do-it-all cargo bike.
<br>
            Designed, built and ridden daily in Copenhagen and across the globe.
            <br>
            9 colour options and a diverse component and accessory line.
<br>
            With quick delivery and availability, competitive pricing and a highly developed system of components and accessories, the Bullitt is the quickest, most flexible and durable solution currently on the market.
<br>
            This buyer’s guide is designed to help you choose the correct Bullitt model and pair you with the most appropriate accessories for your needs.
        </div>
        <button type="button" class="btn btn-default" onclick="wizardButtonClickedback()">Back</button>
        <button type="button" class="btn btn-default" onclick="wizardButtonClicked()">Next Step</button>

    <?php
}

add_shortcode('bikewizard', 'showBikeWizard');

?>

